version: "3.8"

services:
  backend:
    image: kanishka990/incident-backend:latest
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres

  frontend:
    image: kanishka990/incident-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  postgres:
    image: postgres:15
    container_name: postgres_i
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: incidentdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
