version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: incident_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: incidentdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: YOUR_DOCKERHUB_USERNAME/incident-backend:latest
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    restart: always

  frontend:
    image: YOUR_DOCKERHUB_USERNAME/incident-frontend:latest
    depends_on:
      - backend
    ports:
      - "3001:80"
    restart: always

volumes:
  postgres_data:
